필요한 라이브러리를 가져옵니다.

In [1]:
from bs4 import BeautifulSoup
from html_table_parser import parser_functions as parser
import pandas as pd
import requests

크롤링할 주소를 url에 저장한다. 아라시의 음반 목록을 가져온다.

In [2]:
# Crawling
url = 'https://en.wikipedia.org/wiki/Arashi_discography'

해당 url에 대하여 HTTP request를 통해 HTML response를 받는다.

In [3]:
req = requests.get(url)
html = req.text
soup = BeautifulSoup(html, 'html.parser')

해당 웹페이지에서 크롤링하고자 하는 표의 속성을 확인 한후 fina_all() 함수를 통해 HTML에서 해당 표만을 추출합니다. 아래의 경우 HTML에서 class가 sortable wikitable인 table 태그만을 추출하고자 한다.

In [15]:
# 크롤링하고자 하는 표 : <tabl class="wikitable">
tables = soup.find_all('table', attrs={'class' : 'wikitable'})

변수 tables에 담겨있는 정보들을 데이터프레임 형태로 변환한다.

In [41]:
# 데이터 프레임 설정
temp = []
for table in tables :
  table = parser.make2d(table)
  table = pd.DataFrame(table[1:])
  temp.append(table)
df = pd.concat(temp)
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,Title,Album details,JPN[5],TWN[17][B],TWNEA[18][C],KOR[19][D],KORINT[20],Certifications,First week,Total,NaN,NaN
1,Arashi No.1 Ichigou:Arashi wa Arashi o Yobu!,"Released: January 24, 2001\nLabel: Pony Canyon...",1,—,—,—,—,RIAJ: Platinum[21],"267,220","323,030",NaN,NaN
2,Here We Go!,"Released: July 17, 2002\nLabel: J Storm\nForma...",2,—,—,—,—,RIAJ: Gold[22],"110,250","147,811",NaN,NaN
3,How's It Going?,"Released: July 9, 2003\nLabel: J Storm\nFormat...",2,—,—,—,—,RIAJ: Gold[23],"82,461","115,180",NaN,NaN
4,"Iza, Now!","Released: July 21, 2004\nLabel: J Storm\nForma...",1,—,—,—,—,RIAJ: Gold[23],"115,241","151,528",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
77,"""In the Summer""",2020,Ukon Kamimura,[242],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,"""Kite""",2020,Kazuaki Seki,[242],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,"""Whenever You Call""",2020,Hideaki Sunaga,[242],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,"""Party Starters""",2020,Ukyo Inaba,[242],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,"""Do You...?""",2020,Kensuke Kawamura,[242],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

데이터프레임의 간략한 정보를 확인한다.

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242 entries, 0 to 81
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       242 non-null    object
 1   1       242 non-null    object
 2   2       242 non-null    object
 3   3       239 non-null    object
 4   4       143 non-null    object
 5   5       143 non-null    object
 6   6       143 non-null    object
 7   7       135 non-null    object
 8   8       102 non-null    object
 9   9       102 non-null    object
 10  10      38 non-null     object
 11  11      38 non-null     object
dtypes: object(12)
memory usage: 24.6+ KB

크롤링 후 후처리를 한다.

In [43]:
df.columns = ['Title', 'Album details', 'JPN', 'JPNHot',	'TWN', 'TWNEA',	'KOR',	'KORINT',	'Certifications',	'First week',	'Total',	'Album'] # 컬럼명 변경
df.dropna(inplace=True) # 결측치 제거
df.reset_index(drop=True, inplace=True) # 인덱스 재설정
df = df.drop([0], axis=0) # 맨위 행 title 제거
df = df.drop([33],axis = 0)

In [44]:
df

,Title,Album details,JPN,JPNHot,TWN,TWNEA,KOR,KORINT,Certifications,First week,Total,Album
1,"""Troublemaker""",2010,1,1,4,2,7,2,RIAJ: 2× Platinum[23],"542,334","701,686",Boku no Miteiru Fūkei
2,"""Monster""",2010,1,1,11,3,12,2,RIAJ: 2× Platinum[23],"543,269","707,197",Boku no Miteiru Fūkei
3,"""To Be Free""",2010,1,1,9,3,19,4,RIAJ: 2× Platinum[23],"425,978","519,781",Beautiful World
4,"""Love Rainbow""[150][151]",2010,1,1,16,4,30,3,RIAJ: 2× Platinum[23],"528,844","627,523",Beautiful World
5,"""Dear Snow""[152][153]",2010,1,1,—,—,38,4,RIAJ: 2× Platinum[23],"500,730","598,790",Beautiful World
6,"""Hatenai Sora""[154][155]",2010,1,1,8,1,35,13,RIAJ: 2× Platinum[23],"572,050","693,869",Beautiful World
7,"""Lotus""[156][157]",2011,1,1,11,1,29,6,RIAJ: 2× Platinum[23],"541,424","625,935",Beautiful World
8,"""Meikyū Love Song""[158]",2011,1,1,15,3,20,5,RIAJ: 2× Platinum[23],"530,469","647,391",Popcorn
9,"""Wild at Heart""",2012,1,1,7,4,14,2,RIAJ: 2× Platinum[23],"550,014","649,881",Popcorn
10,"""Face Down""",2012,1,1,9,3,36,7,RIAJ: 2× Platinum[23],"526,106","619,940",Popcorn
11,"""Your Eyes""",2012,1,1,14,1,35,10,RIAJ: 2× Platinum[23],"477,820","559,412",Popcorn
12,"""Calling""",2013,1,1,3,2,20,5,RIAJ: 3× Platinum[23],"756,410","881,192",Love
13,"""Breathless""",2013,1,2,3,2,20,5,RIAJ: 3× Platinum[23],"756,410","881,192",Love
14,"""Endless Game""",2013,1,1,—,—,25,5,RIAJ: 2× Platinum[23],"477,869","557,794",Love
15,"""Bittersweet""",2014,1,1,18,3,35,12,RIAJ: 2× Platinum[23],"511,696","591,847",The Digitalian
16,"""Guts!""",2014,1,1,7,1,57,12,RIAJ: 2× Platinum[23],"501,493","609,184",The Digitalian
17,"""Daremo Shiranai""",2014,1,1,14,3,48,13,RIAJ: 2× Platinum[23],"461,622","525,055",The Digitalian
18,"""Sakura""",2015,1,1,—,1,66,16,RIAJ: 2× Platinum[23],"465,381","521,067",Japonism
19,"""Aozora no Shita, Kimi no Tonari""",2015,1,1,—,1,56,11,RIAJ: 2× Platinum[23],"501,010","571,597",Japonism
20,"""Ai o Sakebe""",2015,1,1,—,2,62,19,RIAJ: 2× Platinum[23],"462,550","530,330",Are You Happy?
21,"""Fukkatsu Love""",2016,1,1,—,4,77,17,RIAJ: 2× Platinum[23],"485,006","534,954",Are You Happy?
22,"""I Seek""",2016,1,1,1,—,68,8,RIAJ: 3× Platinum[23],"737,951","829,305",Are You Happy?
23,"""Daylight""",2016,1,21,1,—,68,8,RIAJ: 3× Platinum[23],"737,951","829,305",Are You Happy?
24,"""Power of the Paradise""",2016,1,1,—,—,76,7,RIAJ: 2× Platinum[23],"422,418","475,880",Untitled
25,"""I'll Be There""",2017,1,1,—,—,66,6,RIAJ: 2× Platinum[23],"393,555","438,613",Untitled
26,"""Tsunagu""",2017,1,1,—,—,75,8,RIAJ: Platinum[23],"389,311","434,893",Untitled
27,"""Doors (Yūki no Kiseki)""",2017,1,1,—,—,58,1,RIAJ: 2× Platinum[23],"571,386","640,605",5x20 All the Best!! 1999–2019
28,"""Find the Answer""",2018,1,1,—,—,45,1,RIAJ: Platinum[23],"395,205","440,307",5x20 All the Best!! 1999–2019
29,"""Natsu Hayate""",2018,1,1,—,—,46,2,RIAJ: 2× Platinum[23],"470,780","541,491",5x20 All the Best!! 1999–2019
30,"""Kimi no Uta""[159]",2018,1,1,1,—,43,3,RIAJ: Platinum[23],"373,000[160]","428,748",5x20 All the Best!! 1999–2019
31,"""Brave""",2019,1,2,—,1,55,—,RIAJ: 3× Platinum[23],"667,615[161]","713,159",This Is Arashi
32,"""Turning Up""",2019,—[R],2,—,—,—,—,,"28,000[163]","130,071[164]",This Is Arashi
34,"""In the Summer""[170]",2020,—[S],5,1,—,23,—,,"JPN: 52,904 (DL)",,This Is Arashi
35,"""Kite""[172]",2020,1,1,3,1,—,—,RIAJ: Million[23],"JPN: 910,860 (CD)\nJPN: 12,829 (DL)","JPN: 1,164,965 (CD)\nJPN: 151,921 (DL)",This Is Arashi
36,"""Whenever You Call""[173][174]",2020,—[T],6,1,—,10,51,,"JPN: 61,054 (DL)","JPN: 94,289 (DL)",This Is Arashi
37,"""Party Starters""[176][177]",2020,—[U],7,2,—,—,145,,"JPN: 40,864 (DL)",,This Is Arashi

In [45]:
df.to_csv('WikipediaTable.csv')